// Copyright 2016 Proyectos y Sistemas de Mantenimiento SL (eProsima).
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

/*!
 * @file data1.h
 * This header file contains the declaration of the described types in the IDL file.
 *
 * This file was generated by the tool gen.
 */

#ifndef _data1_H_
#define _data1_H_

#ifdef __cplusplus
extern "C"
{
#endif

#include <stdint.h>
#include <stdbool.h>

/*!
 * @brief This struct represents the structure Student defined by the user in the IDL file.
 * @ingroup data1
 */
typedef struct Student
{
    char name[255];

    int32_t number;
    int32_t grade;
    char hobby[3][255];

} Student;

struct ucdrBuffer;

bool Student_serialize_topic(struct ucdrBuffer* writer, const Student* topic);
bool Student_deserialize_topic(struct ucdrBuffer* reader, Student* topic);
uint32_t Student_size_of_topic(const Student* topic, uint32_t size);


#ifdef __cplusplus
}
#endif

#endif // _data1_H_